### ISSUE TITLE
Detailed training parameters

### ISSUE THREAD

**Issue by scikkk** [pipilurj/G-LLaVA#3]
![image](https://github.com/pipilurj/G-LLaVA/assets/77485593/9f58a648-7ca3-4ebd-8e5d-e6a83fc0aca7)
Thank you for your good work, but I found that the parameters in the training script in the code repository are different from those in the article. What are the real training parameters?

**Comment by pipilurj** [comment]
Hi, thanks a lot for your interest in our work. We made a typo in the article regarding the batch size. Please use the provided script to conduct training. We will fix the typo in the article in our next version.
